### ISSUE TITLE
BangerEvent firing too often

### ISSUE THREAD

**Issue by StefanEilander2** [rickklaasboer/wego-overseer#26]
https://www.npmjs.com/package/languagedetect

**Comment by StefanEilander2** [comment]
Languagedetect doesnt seem te work, maybe there should be a chance of it firing? Like 1/30 words ending on -er

**Comment by rickklaasboer** [comment]
Maybe using something like [Amazon Comprehend](https://docs.aws.amazon.com/comprehend/latest/dg/what-is.html) would also work.

**Comment by rickklaasboer** [comment]
Joke got old real fast, event disabled for now.
