### ISSUE TITLE
Broken Regex?

### ISSUE THREAD

**Issue by Joehoel** [rickklaasboer/wego-overseer#286]
![image](https://github.com/rickklaasboer/wego-overseer/assets/31251240/a234efb8-df5e-49ec-b9f9-25f098e9d33a)

**Comment by Jessuhh** [comment]
Works on my machine

**Comment by Jessuhh** [comment]
Please provide some more context

**Comment by rickklaasboer** [comment]
Regex works good enough as is, could maybe tweak it a bit in the future.
