### ISSUE TITLE
Don't use decimal point as thousands delimeter

### ISSUE THREAD

**Issue by Jessuhh** [rickklaasboer/wego-overseer#376]
![image](https://github.com/rickklaasboer/wego-overseer/assets/58728143/bf4e0684-9051-4a81-abd2-a705649ebb57)

Instead of `202.397` opt for `202,397`. Or go for a truly international variant using a space (or thin space ` `) `202 397` or underscore (`_`) `202_397`

For more information, check out this wikipedia page: https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

**Comment by rickklaasboer** [comment]
In my personal opinion I don't really mind using either `,` or `.` or maybe just ` `. But I think the "Dutch" way works just fine. If anybody has a really strong opinion about this, please leave a comment as to why :)

**Comment by Joehoel** [comment]
🧀

**Comment by rickklaasboer** [comment]
I guess it works fine as is, feel free to open up a pull request though!
