### ISSUE TITLE
AOC leaderboard V2

### ISSUE THREAD

**Issue by Kabelbaan** [rickklaasboer/wego-overseer#57]
Embedded AOC leaderboard with bootiful design

for next year tho

**Comment by Jessuhh** [comment]
I saw some changes related to the AOC command in #65. Does that implement this enhancement @rickklaasboer? I'm unsure what exactly you mean by this enhancement. Do you mind elaborating @Kabelbaan?

**Comment by Kabelbaan** [comment]
Discord [embeds](https://discordjs.guide/popular-topics/embeds.html#embed-preview) like this:

![image](https://user-images.githubusercontent.com/47702083/207675289-bdea0306-80c3-41b7-9068-e03e30ae2454.png)

**Comment by rickklaasboer** [comment]
Please reopen when actually needed.
