### ISSUE TITLE
Wego overseer is able to receive karma

### ISSUE THREAD

**Issue by rickklaasboer** [rickklaasboer/wego-overseer#80]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/16895531/208431826-d6470804-0b94-44b2-a0b3-e9eb67c8c7c0.png">

This should not be the case.

**Comment by Jessuhh** [comment]
To be honest I like the idea of the bot having karma and us just downvoting it straight to hell with all it's stupid dad jokes
