### ISSUE TITLE
Link embeds don't fire the KarmaMessageCreateEvent

### ISSUE THREAD

**Issue by NiekKleverkamp** [rickklaasboer/wego-overseer#89]
When posting an embedded link in a karma channel that message doesn't fire the `KarmaMessageCreateEvent`

**Comment by rickklaasboer** [comment]
![image](https://user-images.githubusercontent.com/16895531/209815754-4764dcdf-bcb4-4a0e-ba66-f68d28946128.png)
Seems to be working sometimes, my guess is Discord sometimes takes a while to create the embed, resulting in an empty embeds/attatchments array when the event is received.

**Comment by Jessuhh** [comment]
Can probably be solved by checking if a message contains a link. Assuming every link in a karma channel is content. Would allow us to vote in #weg_music on songs as well
![image](https://user-images.githubusercontent.com/58728143/212113315-b42cf997-630b-4fb4-a31a-252750577ee1.png)
