### ISSUE TITLE
Show actual message instead of link for quality content

### ISSUE THREAD

**Issue by Joehoel** [rickklaasboer/wego-overseer#93]
![2023-01-19 at 15 46 05@2x](https://user-images.githubusercontent.com/31251240/213472540-504466de-2b8b-4f59-99d0-3f3216d6bb89.jpg)
Instead of showing a link to the message, just show the message content itself (and the link)

**Comment by Jessuhh** [comment]
This is only the case if the message contains a video

**Comment by rickklaasboer** [comment]
We cannot embed videos, as per [discord docs](https://discord.com/developers/docs/resources/channel#create-message).

> For the embed object, you can set every field except type (it will be rich regardless of if you try to set it), provider, video, and any height, width, or proxy_url values for images.
