### ISSUE TITLE
Better error formatting

### ISSUE THREAD

**Issue by Jessuhh** [rickklaasboer/wego-overseer#95]
![image](https://user-images.githubusercontent.com/58728143/213712599-47c2b690-857e-4a22-a3d0-91c77361d173.png)

**Comment by rickklaasboer** [comment]
This can already be achieved by piping the console output to `bunyan`.

For example:

```sh
yarn dev | yarn bunyan
```

Although, this doesn't seem to work while using `tsx` as our build tool. We should probably figure out why this is instead. We could also try using rollup/esbuild/vite/webpack instead of tsx.

**Comment by rickklaasboer** [comment]
Looks like this was fixed somehow, closing as completed.
